### ISSUE TITLE
is there any way to support full screen ?

### ISSUE THREAD

**Issue by gdg4dev** [gsioteam/kuma_player#1]

**Comment by gsioteam** [comment]
I think the fullscreen feature is not appear in `video_player`, that mean in flutter we could make any widget fullscreen by using `SystemChrome.setEnabledSystemUIOverlays([]) ` and `Overlay`. I am writing my app I will face this problem soon, I think when I do this I would post a demo here.

**Comment by gsioteam** [comment]
Ok, I found it is very easy. just follow this guide [https://www.programmersought.com/article/75575318163/](https://www.programmersought.com/article/75575318163/)
